// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2025, 1:21:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/ibuky/paralleddit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ibuky/paralleddit/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ibuky/paralleddit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ibuky/paralleddit/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ibuky/paralleddit/plugins/**/*.{js,ts,mjs}","/home/ibuky/paralleddit/composables/**/*.{js,ts,mjs}","/home/ibuky/paralleddit/utils/**/*.{js,ts,mjs}","/home/ibuky/paralleddit/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ibuky/paralleddit/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ibuky/paralleddit/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;